services:
  - type: web
    name: source-vault
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: node_modules/.bin/next start -p $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: S3_BUCKET
        sync: false
      - key: S3_ENDPOINT
        sync: false
      - key: S3_ACCESS_KEY_ID
        sync: false
      - key: S3_SECRET_ACCESS_KEY
        sync: false
      - key: S3_PUBLIC_URL
        sync: false
      - key: S3_REGION
        sync: false
