'use client';

import { useMemo, useRef, useState } from 'react';

type CellValue = string | number | boolean | null;
type ParsedSheet = { name: string; rows: CellValue[][]; rowCount: number; truncated: boolean };
type ParsedWorkbook = { filename: string; sheets: ParsedSheet[] };
type VisualType = 'histogram'|'box'|'bubble'|'funnel'|'slope'|'beeswarm'|'treemap'|'network'|'sankey'|'timeline'|'globe';

type Col = { index:number; name:string; numeric:boolean };

const TYPES: Array<{id:VisualType;name:string;family:string;note:string}> = [
  {id:'histogram',name:'Histogram',family:'Statistical',note:'Distribution of a numeric field'},
  {id:'box',name:'Box plot',family:'Statistical',note:'Median, quartiles and outliers by category'},
  {id:'bubble',name:'Bubble chart',family:'Relationships',note:'X, Y and size encode three measures'},
  {id:'beeswarm',name:'Beeswarm',family:'Statistical',note:'Dense distributions without bins'},
  {id:'funnel',name:'Funnel',family:'Business',note:'Stage-by-stage dropoff'},
  {id:'slope',name:'Slope chart',family:'Business',note:'Compare two values across categories'},
  {id:'treemap',name:'Treemap',family:'Hierarchy',note:'Part-to-whole hierarchy'},
  {id:'network',name:'Force network',family:'Network',note:'Source → target relationships'},
  {id:'sankey',name:'Sankey flow',family:'Network',note:'Weighted flow between categories'},
  {id:'timeline',name:'Timeline',family:'Story',note:'Events placed on a temporal axis'},
  {id:'globe',name:'Globe',family:'Maps',note:'Global latitude / longitude signals'},
];

const stringValue=(v:CellValue)=>v==null?'':String(v);
function num(v:CellValue){ if(typeof v==='number'&&Number.isFinite(v)) return v; const n=Number(stringValue(v).replace(/[,$%]/g,'').trim()); return Number.isFinite(n)?n:null; }
function fmt(v:number){return new Intl.NumberFormat('en-US',{maximumFractionDigits:2,notation:Math.abs(v)>=100000?'compact':'standard'}).format(v)}
function quantile(values:number[],q:number){if(!values.length)return 0;const s=[...values].sort((a,b)=>a-b),p=(s.length-1)*q,b=Math.floor(p),r=p-b;return s[b]+(s[b+1]!==undefined?r*(s[b+1]-s[b]):0)}
function downloadText(name:string,text:string){const blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

function Svg({children}:{children:React.ReactNode}){return <svg viewBox="0 0 1000 560" className="av-svg">{children}</svg>}

function Histogram({rows,col}:{rows:CellValue[][];col:Col}){const vals=rows.flatMap(r=>{const n=num(r[col.index]);return n===null?[]:[n]});if(!vals.length)return <Empty/>;const min=Math.min(...vals),max=Math.max(...vals),bins=18,w=(max-min||1)/bins,counts=Array.from({length:bins},()=>0);vals.forEach(v=>counts[Math.min(bins-1,Math.floor((v-min)/(w||1)))]++);const m=Math.max(...counts,1);return <Svg>{counts.map((c,i)=>{const bw=870/bins,x=75+i*bw,h=c/m*400;return <g key={i}><rect x={x+2} y={455-h} width={bw-4} height={h} rx="4"/><text x={x+bw/2} y="482" textAnchor="middle">{fmt(min+i*w)}</text></g>})}<text x="75" y="35" className="av-kicker">{vals.length.toLocaleString()} observations</text></Svg>}

function BoxPlot({rows,cat,measure}:{rows:CellValue[][];cat:Col;measure:Col}){const groups=new Map<string,number[]>();for(const r of rows){const k=stringValue(r[cat.index]).trim()||'(blank)',n=num(r[measure.index]);if(n===null)continue;if(!groups.has(k))groups.set(k,[]);groups.get(k)!.push(n)}const items=[...groups.entries()].slice(0,12).map(([k,v])=>({k,min:Math.min(...v),q1:quantile(v,.25),med:quantile(v,.5),q3:quantile(v,.75),max:Math.max(...v)}));if(!items.length)return <Empty/>;const lo=Math.min(...items.map(i=>i.min)),hi=Math.max(...items.map(i=>i.max)),range=hi-lo||1;return <Svg>{items.map((d,i)=>{const y=55+i*38,px=(v:number)=>210+(v-lo)/range*700;return <g key={d.k}><text x="20" y={y+5}>{d.k.slice(0,24)}</text><line x1={px(d.min)} x2={px(d.max)} y1={y} y2={y} className="av-thin"/><rect x={px(d.q1)} y={y-10} width={Math.max(2,px(d.q3)-px(d.q1))} height="20" rx="3"/><line x1={px(d.med)} x2={px(d.med)} y1={y-14} y2={y+14} className="av-median"/></g>})}</Svg>}

function Bubble({rows,x,y,size}:{rows:CellValue[][];x:Col;y:Col;size:Col}){const pts=rows.flatMap((r,i)=>{const xv=num(r[x.index]),yv=num(r[y.index]),sv=num(r[size.index]);return xv===null||yv===null||sv===null?[]:[{x:xv,y:yv,s:Math.abs(sv),i}]}).slice(0,800);if(!pts.length)return <Empty/>;const xs=pts.map(p=>p.x),ys=pts.map(p=>p.y),ss=pts.map(p=>p.s),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),smax=Math.max(...ss,1);return <Svg>{pts.map(p=><circle key={p.i} cx={70+(p.x-xmin)/(xmax-xmin||1)*860} cy={490-(p.y-ymin)/(ymax-ymin||1)*420} r={4+Math.sqrt(p.s/smax)*22} opacity=".58"/>)}</Svg>}

function Funnel({rows,cat,measure}:{rows:CellValue[][];cat:Col;measure:Col}){const map=new Map<string,number>();for(const r of rows){const k=stringValue(r[cat.index]).trim()||'(blank)',n=num(r[measure.index]);if(n!==null)map.set(k,(map.get(k)||0)+n)}const items=[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,9),max=items[0]?.[1]||1;if(!items.length)return <Empty/>;return <Svg>{items.map(([k,v],i)=>{const width=160+v/max*620,x=500-width/2,y=45+i*52;return <g key={k}><path d={`M${x} ${y} H${x+width} L${x+width-24} ${y+40} H${x+24} Z`}/><text x="500" y={y+25} textAnchor="middle" className="av-invert">{k.slice(0,28)} · {fmt(v)}</text></g>})}</Svg>}

function Slope({rows,cat,a,b}:{rows:CellValue[][];cat:Col;a:Col;b:Col}){const points=rows.flatMap((r,i)=>{const x=num(r[a.index]),y=num(r[b.index]);return x===null||y===null?[]:[{k:stringValue(r[cat.index])||`Row ${i+1}`,a:x,b:y}]}).slice(0,18);if(!points.length)return <Empty/>;const all=points.flatMap(p=>[p.a,p.b]),lo=Math.min(...all),hi=Math.max(...all),py=(v:number)=>490-(v-lo)/(hi-lo||1)*420;return <Svg><text x="230" y="35" textAnchor="middle">{a.name}</text><text x="770" y="35" textAnchor="middle">{b.name}</text>{points.map((p,i)=><g key={i}><line x1="230" x2="770" y1={py(p.a)} y2={py(p.b)} opacity=".45"/><circle cx="230" cy={py(p.a)} r="6"/><circle cx="770" cy={py(p.b)} r="6"/><text x="215" y={py(p.a)+4} textAnchor="end">{p.k.slice(0,18)}</text></g>)}</Svg>}

function Beeswarm({rows,col}:{rows:CellValue[][];col:Col}){const vals=rows.flatMap((r,i)=>{const n=num(r[col.index]);return n===null?[]:[{v:n,i}]}).slice(0,1500);if(!vals.length)return <Empty/>;const lo=Math.min(...vals.map(d=>d.v)),hi=Math.max(...vals.map(d=>d.v));return <Svg>{vals.map((d,index)=>{const x=75+(d.v-lo)/(hi-lo||1)*850,y=270+Math.sin(index*2.399963)*Math.min(120,10+(index%19)*5);return <circle key={d.i} cx={x} cy={y} r="5" opacity=".5"/>})}</Svg>}

function Treemap({rows,cat,measure}:{rows:CellValue[][];cat:Col;measure:Col}){const map=new Map<string,number>();for(const r of rows){const k=stringValue(r[cat.index]).trim()||'(blank)',n=num(r[measure.index]);if(n!==null)map.set(k,(map.get(k)||0)+Math.abs(n))}const items=[...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,20),total=items.reduce((s,i)=>s+i[1],0)||1;if(!items.length)return <Empty/>;let x=40,y=40,rowH=0;return <Svg>{items.map(([k,v],i)=>{const area=v/total*820*440,w=Math.max(90,Math.min(380,Math.sqrt(area*1.65))),h=Math.max(55,area/w);if(x+w>940){x=40;y+=rowH+8;rowH=0}const xx=x,yy=y;x+=w+8;rowH=Math.max(rowH,h);return <g key={k}><rect x={xx} y={yy} width={w} height={h} rx="8" opacity={.35+.55*(1-i/items.length)}/><text x={xx+10} y={yy+22}>{k.slice(0,20)}</text><text x={xx+10} y={yy+42} className="av-small">{fmt(v)}</text></g>})}</Svg>}

function Network({rows,source,target,weight,sankey=false}:{rows:CellValue[][];source:Col;target:Col;weight?:Col;sankey?:boolean}){const links=rows.flatMap(r=>{const s=stringValue(r[source.index]).trim(),t=stringValue(r[target.index]).trim(),w=weight?num(r[weight.index])??1:1;return !s||!t?[]:[{s,t,w:Math.abs(w)}]}).slice(0,700);if(!links.length)return <Empty/>;const names=[...new Set(links.flatMap(l=>[l.s,l.t]))].slice(0,80),index=new Map(names.map((n,i)=>[n,i])),maxW=Math.max(...links.map(l=>l.w),1);if(sankey){const left=[...new Set(links.map(l=>l.s))].slice(0,25),right=[...new Set(links.map(l=>l.t))].slice(0,25),ly=new Map(left.map((n,i)=>[n,50+i*(450/Math.max(1,left.length-1))])),ry=new Map(right.map((n,i)=>[n,50+i*(450/Math.max(1,right.length-1))]));return <Svg>{links.filter(l=>ly.has(l.s)&&ry.has(l.t)).map((l,i)=><path key={i} d={`M190 ${ly.get(l.s)} C420 ${ly.get(l.s)},580 ${ry.get(l.t)},810 ${ry.get(l.t)}`} fill="none" strokeWidth={1+8*l.w/maxW} opacity=".18"/>)}{left.map(n=><g key={n}><circle cx="180" cy={ly.get(n)} r="7"/><text x="165" y={(ly.get(n)||0)+4} textAnchor="end">{n.slice(0,18)}</text></g>)}{right.map(n=><g key={n}><circle cx="820" cy={ry.get(n)} r="7"/><text x="835" y={(ry.get(n)||0)+4}>{n.slice(0,18)}</text></g>)}</Svg>}
const pos=names.map((n,i)=>{const a=i/names.length*Math.PI*2,r=120+(i%5)*45;return{name:n,x:500+Math.cos(a)*r,y:280+Math.sin(a)*r}});return <Svg>{links.map((l,i)=>{const a=pos[index.get(l.s)??0],b=pos[index.get(l.t)??0];return <line key={i} x1={a.x} y1={a.y} x2={b.x} y2={b.y} strokeWidth={.5+4*l.w/maxW} opacity=".15"/>})}{pos.map((p,i)=><g key={p.name}><circle cx={p.x} cy={p.y} r={7+Math.min(12,links.filter(l=>l.s===p.name||l.t===p.name).length)} /><text x={p.x+12} y={p.y+4}>{p.name.slice(0,16)}</text></g>)}</Svg>}

function Timeline({rows,date,label}:{rows:CellValue[][];date:Col;label:Col}){const pts=rows.flatMap((r,i)=>{const d=Date.parse(stringValue(r[date.index]));return Number.isFinite(d)?[{d,label:stringValue(r[label.index])||`Event ${i+1}`,i}]:[]}).slice(0,200);if(!pts.length)return <Empty/>;const lo=Math.min(...pts.map(p=>p.d)),hi=Math.max(...pts.map(p=>p.d));return <Svg><line x1="80" x2="920" y1="280" y2="280" className="av-thin"/>{pts.map((p,i)=>{const x=80+(p.d-lo)/(hi-lo||1)*840,up=i%2===0,y=up?170:390;return <g key={p.i}><line x1={x} x2={x} y1="280" y2={y} className="av-thin"/><circle cx={x} cy="280" r="6"/><text x={x} y={up?y-8:y+18} textAnchor="middle">{p.label.slice(0,18)}</text></g>)}</Svg>}

function Globe({rows,lat,lon,size,rotation}:{rows:CellValue[][];lat:Col;lon:Col;size?:Col;rotation:number}){const pts=rows.flatMap((r,i)=>{const la=num(r[lat.index]),lo=num(r[lon.index]),s=size?Math.abs(num(r[size.index])||1):1;return la===null||lo===null?[]:[{la,lo,s,i}]}).slice(0,1400),maxS=Math.max(...pts.map(p=>p.s),1),cx=500,cy=280,R=210,rot=rotation*Math.PI/180;const project=(la:number,lo:number)=>{const phi=la*Math.PI/180,lambda=lo*Math.PI/180+rot,cosc=Math.cos(phi)*Math.cos(lambda);return{x:cx+R*Math.cos(phi)*Math.sin(lambda),y:cy-R*Math.sin(phi),visible:cosc>=0}};return <Svg><defs><radialGradient id="g"><stop offset="0" stopColor="#173c5a"/><stop offset="1" stopColor="#07131f"/></radialGradient></defs><circle cx={cx} cy={cy} r={R} fill="url(#g)" strokeWidth="2"/>{[-60,-30,0,30,60].map(la=>{const pts=Array.from({length:73},(_,i)=>project(la,-180+i*5)).filter(p=>p.visible);return <polyline key={la} points={pts.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" className="av-globe-grid"/>})}{[-150,-120,-90,-60,-30,0,30,60,90,120,150].map(lo=>{const pts=Array.from({length:37},(_,i)=>project(-90+i*5,lo)).filter(p=>p.visible);return <polyline key={lo} points={pts.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" className="av-globe-grid"/>})}{pts.map(p=>{const q=project(p.la,p.lo);return q.visible?<circle key={p.i} cx={q.x} cy={q.y} r={3+Math.sqrt(p.s/maxS)*9} className="av-globe-point"/>:null})}</Svg>}

function Empty(){return <div className="av-empty"><strong>Choose compatible columns to render this visual.</strong></div>}

export default function AdvancedVisualLab(){const input=useRef<HTMLInputElement>(null),[wb,setWb]=useState<ParsedWorkbook|null>(null),[sheet,setSheet]=useState(0),[header,setHeader]=useState(0),[type,setType]=useState<VisualType>('histogram'),[a,setA]=useState(''),[b,setB]=useState(''),[c,setC]=useState(''),[rotation,setRotation]=useState(0),[loading,setLoading]=useState(false),[error,setError]=useState('');
async function load(file:File){setLoading(true);setError('');try{const f=new FormData();f.append('file',file);const r=await fetch('/api/data/parse',{method:'POST',body:f}),j=await r.json();if(!r.ok)throw new Error(j.error||'Could not parse file');setWb(j);setSheet(0);setHeader(0);setA('');setB('');setC('')}catch(e){setError(e instanceof Error?e.message:'Could not parse file')}finally{setLoading(false)}}
const rows=wb?.sheets[sheet]?.rows||[],cols=useMemo<Col[]>(()=>{const max=Math.max(0,...rows.slice(0,100).map(r=>r.length));return Array.from({length:max},(_,i)=>{const vals=rows.slice(header+1,header+101).map(r=>r[i]),numeric=vals.filter(v=>num(v)!==null).length>=Math.max(2,vals.filter(v=>stringValue(v).trim()).length*.7);return{index:i,name:stringValue(rows[header]?.[i]).trim()||`Column ${i+1}`,numeric}})},[rows,header]),data=rows.slice(header+1).filter(r=>r.some(v=>stringValue(v).trim()));
const ca=cols.find(x=>String(x.index)===a),cb=cols.find(x=>String(x.index)===b),cc=cols.find(x=>String(x.index)===c);let visual:React.ReactNode=<Empty/>;if(ca){if(type==='histogram'&&ca.numeric)visual=<Histogram rows={data} col={ca}/>;if(type==='beeswarm'&&ca.numeric)visual=<Beeswarm rows={data} col={ca}/>;if(type==='box'&&cb?.numeric)visual=<BoxPlot rows={data} cat={ca} measure={cb}/>;if(type==='bubble'&&ca.numeric&&cb?.numeric&&cc?.numeric)visual=<Bubble rows={data} x={ca} y={cb} size={cc}/>;if(type==='funnel'&&cb?.numeric)visual=<Funnel rows={data} cat={ca} measure={cb}/>;if(type==='slope'&&cb?.numeric&&cc?.numeric)visual=<Slope rows={data} cat={ca} a={cb} b={cc}/>;if(type==='treemap'&&cb?.numeric)visual=<Treemap rows={data} cat={ca} measure={cb}/>;if(type==='network'&&cb)visual=<Network rows={data} source={ca} target={cb} weight={cc?.numeric?cc:undefined}/>;if(type==='sankey'&&cb)visual=<Network rows={data} source={ca} target={cb} weight={cc?.numeric?cc:undefined} sankey/>;if(type==='timeline'&&cb)visual=<Timeline rows={data} date={ca} label={cb}/>;if(type==='globe'&&ca.numeric&&cb?.numeric)visual=<Globe rows={data} lat={ca} lon={cb} size={cc?.numeric?cc:undefined} rotation={rotation}/>}
const families=[...new Set(TYPES.map(t=>t.family))];return <div className="av-app"><aside className="av-sidebar"><a href="/vault" className="av-back">← Data Studio</a><h1>Advanced Visual Lab</h1><p>Experimental analysis modes drawn from the supplied D3, force-graph, globe and storytelling references.</p>{families.map(f=><section key={f}><h2>{f}</h2>{TYPES.filter(t=>t.family===f).map(t=><button key={t.id} className={type===t.id?'active':''} onClick={()=>setType(t.id)}><strong>{t.name}</strong><span>{t.note}</span></button>)}</section>)}</aside><main className="av-main"><header><div><span>ADVANCED VISUALIZATION</span><h2>{TYPES.find(t=>t.id===type)?.name}</h2></div>{wb?<div className="av-file"><strong>{wb.filename}</strong><span>{data.length.toLocaleString()} rows</span></div>:null}</header>{!wb?<div className="av-upload"><input ref={input} type="file" accept=".xlsx,.csv,.tsv" onChange={e=>{const f=e.target.files?.[0];if(f)load(f)}}/><h2>Load a workbook</h2><p>The lab uses the same spreadsheet parser as the main Data Studio.</p><button onClick={()=>input.current?.click()} disabled={loading}>{loading?'Reading…':'Choose file'}</button>{error&&<em>{error}</em>}</div>:<><div className="av-controls"><label>Sheet<select value={sheet} onChange={e=>{setSheet(Number(e.target.value));setHeader(0)}}>{wb.sheets.map((s,i)=><option key={s.name+i} value={i}>{s.name}</option>)}</select></label><label>Header row<select value={header} onChange={e=>setHeader(Number(e.target.value))}>{rows.slice(0,12).map((_,i)=><option key={i} value={i}>Row {i+1}</option>)}</select></label><label>Primary / category<select value={a} onChange={e=>setA(e.target.value)}><option value="">Choose column</option>{cols.map(x=><option key={x.index} value={x.index}>{x.name}{x.numeric?' · #':''}</option>)}</select></label><label>Secondary<select value={b} onChange={e=>setB(e.target.value)}><option value="">Choose column</option>{cols.map(x=><option key={x.index} value={x.index}>{x.name}{x.numeric?' · #':''}</option>)}</select></label><label>Third / weight<select value={c} onChange={e=>setC(e.target.value)}><option value="">Optional</option>{cols.map(x=><option key={x.index} value={x.index}>{x.name}{x.numeric?' · #':''}</option>)}</select></label>{type==='globe'&&<label>Rotate globe<input type="range" min="-180" max="180" value={rotation} onChange={e=>setRotation(Number(e.target.value))}/></label>}</div><section className="av-stage">{visual}</section><footer><button onClick={()=>downloadText('advanced-visual-project.json',JSON.stringify({type,sheet:wb.sheets[sheet]?.name,headerRow:header+1,columns:{primary:ca?.name,secondary:cb?.name,third:cc?.name}},null,2))}>Export visual config</button><a href="/vault">Return to publication editor →</a></footer></>}</main></div>}
